/* auto-generated by NAPI-RS */
/* eslint-disable */
/** Camera instance for capturing frames */
export declare class Camera {
  /** Create a new camera instance */
  constructor(cameraIndex: string)
  /** Capture a single frame from camera */
  captureFrame(): Frame
}

export interface CameraDevice {
  index: string
  name: string
}

export interface Frame {
  data: Buffer
  width: number
  height: number
  fps: number
}

/** List all available cameras */
export declare function listCameras(): Array<CameraDevice>
