/* auto-generated by NAPI-RS */
/* eslint-disable */
/**
 * Camera instance for capturing frames
 * The user is responsible for managing the lifecycle of this camera
 */
export declare class Camera {
  /**
   * Create a new camera instance with the given index
   * The camera stream is opened immediately
   */
  constructor(cameraIndex: string)
  /**
   * Capture a single frame from the camera
   * Returns the frame as RGBA buffer with width and height
   */
  captureFrame(): Frame
}

export interface CameraDevice {
  index: string
  name: string
}

export interface Frame {
  data: Buffer
  width: number
  height: number
}

/** List all available cameras */
export declare function listCameras(): Array<CameraDevice>
