/* eslint-disable */
/* prettier-ignore */

/* auto-generated by NAPI-RS */

const __nodeFs = require('node:fs')
const __nodePath = require('node:path')
const { WASI: __nodeWASI } = require('node:wasi')
const { Worker } = require('node:worker_threads')

const {
  createOnMessage: __wasmCreateOnMessageForFsProxy,
  getDefaultContext: __emnapiGetDefaultContext,
  instantiateNapiModuleSync: __emnapiInstantiateNapiModuleSync,
} = require('@napi-rs/wasm-runtime')

const __rootDir = __nodePath.parse(process.cwd()).root

const __wasi = new __nodeWASI({
  version: 'preview1',
  env: process.env,
  preopens: {
    [__rootDir]: __rootDir,
  }
})

const __emnapiContext = __emnapiGetDefaultContext()

const __sharedMemory = new WebAssembly.Memory({
  initial: 4000,
  maximum: 65536,
  shared: true,
})

let __wasmFilePath = __nodePath.join(__dirname, 'nokhwa-node.wasm32-wasi.wasm')
const __wasmDebugFilePath = __nodePath.join(__dirname, 'nokhwa-node.wasm32-wasi.debug.wasm')

if (__nodeFs.existsSync(__wasmDebugFilePath)) {
  __wasmFilePath = __wasmDebugFilePath
} else if (!__nodeFs.existsSync(__wasmFilePath)) {
  try {
    __wasmFilePath = require.resolve('nokhwa-node-wasm32-wasi/nokhwa-node.wasm32-wasi.wasm')
  } catch {
    throw new Error('Cannot find nokhwa-node.wasm32-wasi.wasm file, and nokhwa-node-wasm32-wasi package is not installed.')
  }
}

const { instance: __napiInstance, module: __wasiModule, napiModule: __napiModule } = __emnapiInstantiateNapiModuleSync(__nodeFs.readFileSync(__wasmFilePath), {
  context: __emnapiContext,
  asyncWorkPoolSize: (function() {
    const threadsSizeFromEnv = Number(process.env.NAPI_RS_ASYNC_WORK_POOL_SIZE ?? process.env.UV_THREADPOOL_SIZE)
    // NaN > 0 is false
    if (threadsSizeFromEnv > 0) {
      return threadsSizeFromEnv
    } else {
      return 4
    }
  })(),
  reuseWorker: true,
  wasi: __wasi,
  onCreateWorker() {
    const worker = new Worker(__nodePath.join(__dirname, 'wasi-worker.mjs'), {
      env: process.env,
    })
    worker.onmessage = ({ data }) => {
      __wasmCreateOnMessageForFsProxy(__nodeFs)(data)
    }

    // The main thread of Node.js waits for all the active handles before exiting.
    // But Rust threads are never waited without `thread::join`.
    // So here we hack the code of Node.js to prevent the workers from being referenced (active).
    // According to https://github.com/nodejs/node/blob/19e0d472728c79d418b74bddff588bea70a403d0/lib/internal/worker.js#L415,
    // a worker is consist of two handles: kPublicPort and kHandle.
    {
      const kPublicPort = Object.getOwnPropertySymbols(worker).find(s =>
        s.toString().includes("kPublicPort")
      );
      if (kPublicPort) {
        worker[kPublicPort].ref = () => {};
      }

      const kHandle = Object.getOwnPropertySymbols(worker).find(s =>
        s.toString().includes("kHandle")
      );
      if (kHandle) {
        worker[kHandle].ref = () => {};
      }

      worker.unref();
    }
    return worker
  },
  overwriteImports(importObject) {
    importObject.env = {
      ...importObject.env,
      ...importObject.napi,
      ...importObject.emnapi,
      memory: __sharedMemory,
    }
    return importObject
  },
  beforeInit({ instance }) {
    for (const name of Object.keys(instance.exports)) {
      if (name.startsWith('__napi_register__')) {
        instance.exports[name]()
      }
    }
  },
})
module.exports = __napiModule.exports
module.exports.Camera = __napiModule.exports.Camera
module.exports.CameraBuffer = __napiModule.exports.CameraBuffer
module.exports.allKnownCameraControls = __napiModule.exports.allKnownCameraControls
module.exports.ApiBackend = __napiModule.exports.ApiBackend
module.exports.bufBgrToRgb = __napiModule.exports.bufBgrToRgb
module.exports.bufMjpegToRgb = __napiModule.exports.bufMjpegToRgb
module.exports.bufNv12ToRgb = __napiModule.exports.bufNv12ToRgb
module.exports.bufYuyv422ToRgb = __napiModule.exports.bufYuyv422ToRgb
module.exports.colorFrameFormats = __napiModule.exports.colorFrameFormats
module.exports.FrameFormat = __napiModule.exports.FrameFormat
module.exports.frameFormats = __napiModule.exports.frameFormats
module.exports.KnownCameraControl = __napiModule.exports.KnownCameraControl
module.exports.listCameras = __napiModule.exports.listCameras
module.exports.mjpegToRgb = __napiModule.exports.mjpegToRgb
module.exports.nativeApiBackend = __napiModule.exports.nativeApiBackend
module.exports.nokhwaCheck = __napiModule.exports.nokhwaCheck
module.exports.nv12ToRgb = __napiModule.exports.nv12ToRgb
module.exports.query = __napiModule.exports.query
module.exports.RequestedFormatType = __napiModule.exports.RequestedFormatType
module.exports.yuyv422PredictedSize = __napiModule.exports.yuyv422PredictedSize
module.exports.yuyv422ToRgb = __napiModule.exports.yuyv422ToRgb
